services:
  mysql:
    image: mysql:8
    container_name: walletwave-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Sanit@123
    ports:
      - "3307:3306"   # host:container (use 3307 on host to avoid conflicts)
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pSanit@123"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: walletwave-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: walletwave-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper



  redis:
    image: redis:7.2
    container_name: walletwave-redis
    ports:
      - "6379:6379"


  user-service:
    image: walletwave-user:0.1
    container_name: walletwave-user
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: Sanit@123
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started

  wallet-service:
    image: walletwave-wallet:0.1
    container_name: walletwave-wallet
    ports:
      - "9000:9000"
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: Sanit@123
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started


  transaction-service:
    image: walletwave-transaction:0.1
    container_name: walletwave-transaction
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: Sanit@123
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started

  notification-service:
    image: walletwave-notification:0.1
    container_name: walletwave-notification
    ports:
      - "8090:8090"
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: Sanit@123
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started

volumes:
  mysql_data:
